--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2020/4/12 15:25:09
-- Server version: 5.7.27-log
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE test1;

--
-- Drop table `blog`
--
DROP TABLE IF EXISTS blog;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Set default database
--
USE test1;

--
-- Create table `user`
--
CREATE TABLE user (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(500) DEFAULT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  create_ts INT(11) NOT NULL,
  token VARCHAR(255) DEFAULT NULL,
  last_ts INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UK_user_email` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UK_user_email(email);

--
-- Create index `UK_user_username` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UK_user_username(username);

--
-- Create table `blog`
--
CREATE TABLE blog (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  content TEXT DEFAULT NULL,
  user_id INT(11) UNSIGNED NOT NULL,
  create_ts INT(11) UNSIGNED NOT NULL,
  last_ts INT(11) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE blog 
  ADD CONSTRAINT FK_blog_user_id FOREIGN KEY (user_id)
    REFERENCES user(id) ON DELETE CASCADE;

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;